
pipeline {
    agent {
        docker {
            image 'python:3.13.7-alpine3.22'
        }
    }

    options {
        skipStagesAfterUnstable()
    }

    stages {
        stage('Setup') {
            steps {
                sh '''
                python -m venv venv
                . venv/bin/activate
                pip install -r requirements.txt
                '''
            }
        }

        stage('Build') {
            steps {
                sh '''
                . venv/bin/activate
                python -m py_compile sources/add2vals.py sources/calc.py
                '''

                stash(name: 'compiled-results', includes: 'sources/*.py*')
            }
        }

        stage('Test') {
            steps {
                sh '''
                    . venv/bin/activate
                    py.test --junit-xml test-reports/results.xml sources/test_calc.py
                    '''
            }

            post {
                always {
                    junit 'test-reports/results.xml'
                }
            }
        }

        stage('Deliver') {
            steps {
                echo "Собираю дистрибутив"
            }
            post {
                success {
                    archiveArtifacts artifacts: '**/*.py'
                }
            }
        }
    }
}

